### ISSUE TITLE
Import error windows 

### ISSUE THREAD

**Issue by bussiere** [airtonix/python-markdown-qrcode#1]
Traceback (most recent call last):
  File "D:\Documents\GitHub\Scripts\markd.py", line 4, in <module>
    html = markdown.markdown(text,extensions=['qrcode', 'nl2br'])
  File "C:\Python27\lib\site-packages\markdown__init__.py", line 418, in markdown
    md = Markdown(_args, *_kwargs)
  File "C:\Python27\lib\site-packages\markdown__init__.py", line 139, in **init**
    configs=kwargs.get('extension_configs', {}))
  File "C:\Python27\lib\site-packages\markdown__init__.py", line 165, in registerExtensions
    ext = self.build_extension(ext, configs.get(ext, []))
  File "C:\Python27\lib\site-packages\markdown__init__.py", line 203, in build_extension
    module = **import**(module_name_old_style)
  File "C:\Python27\lib\site-packages\mdx_qrcode__init__.py", line 1, in <module>
    from extension import *
  File "C:\Python27\lib\site-packages\mdx_qrcode\extension.py", line 21, in <module>
    from markdown import etree
ImportError: Failed loading extension 'qrcode' from 'markdown.extensions.qrcode' or 'mdx_qrcode'

**Comment by mearns** [comment]
`etree` is not under `markdown`, it is under `markdown.util`. Assuming this must have been a change to markdown at some point.

**Comment by mearns** [comment]
This has been resolved on my branch, Pull request #2 includes the fix and some new additions.
